const STORAGE_KEY_PREFIX = 'siriusxmws';
const LOCAL_STORAGE_ELEMENTS_SETTINGS_OVERRIDE_FLAG_NAME = 'useOverrideElementsSettings';
const LOCAL_STORAGE_ELEMENTS_SETTINGS_OVERRIDE_DATA_NAME = 'elementsSettings';

export const settingsOverrideFlagKey = `${STORAGE_KEY_PREFIX}_${LOCAL_STORAGE_ELEMENTS_SETTINGS_OVERRIDE_FLAG_NAME}`;
export const settingsOverrideDataKey = `${STORAGE_KEY_PREFIX}_${LOCAL_STORAGE_ELEMENTS_SETTINGS_OVERRIDE_DATA_NAME}`;
