export enum RefreshErrorTypesEnum {
    REFRESH_FAIL_GENERIC = 'REFRESH_FAIL_GENERIC',
    REFRESH_FAIL_MAXIMUM_LIMIT = 'REFRESH_FAIL_MAXIMUM_LIMIT',
    REFRESH_FAIL_MULTIPLE_REQUESTS = 'REFRESH_FAIL_MULTIPLE_REQUESTS',
    TEXT_FAIL_SERVICE_NOT_AVAILABLE = 'TEXT_FAIL_SERVICE_NOT_AVAILABLE',
}

export enum RefreshTypeEnum {
    Signal = 'SIGNAL',
    Text = 'TEXT',
}
