export enum AuthenticationTypeEnum {
    TokenURL = 'TOKEN_URL',
    RidAcctURL = 'RID_ACCT_URL',
    RidLnameURL = 'RID_LNAME_URL',
    Flepz = 'FLEPZ',
    Login = 'LOGIN',
    RadioID = 'RID',
    VIN = 'VIN',
    LicensePlateLookup = 'LPL',
    AccountLookup = 'EMAIL',
    Rflz = 'RFLZ',
    TokenizedEntry = 'TOKENIZED_ENTRY',
}
export enum ErrorTypeEnum {
    System = 'SYSTEM',
    Business = 'BUSINESS',
    User = 'USER',
}
export enum DataLayerDataTypeEnum {
    // Grouped data type
    CustomerInfo = 'customerInfo',
    PlanInfo = 'planInfo',
    DeviceInfo = 'deviceInfo',
    PageInfo = 'pageInfo',
    ErrorInfo = 'errorInfo',
    MetaInfo = 'meta',
    AccountData = 'account',
    OfferData = 'offer',
    PackageDescriptionsData = 'packageDescriptions',
    QuoteData = 'quote',
    UpsellData = 'upsell',
    RenewalOffers = 'renewaloffers',
}
export enum DataLayerActionEnum {
    // Grouped Action
    EnterPaymentFromSubscribeClick = 'payment-info-from-subscribe-click',
    SelectedUpgrade = 'selected-upgrade',
    ContrinueUpgrade = 'continue-upgrade',
    EditSection = 'edit-section',
    CompleteOrder = 'complete-order',
    ViewOrderDetails = 'viewOrderdetails',
    ViewToolTip = 'viewToolTip',
    ChargeAgreementCheck = 'charge-agreement-check',
    SuccessfullRegistration = 'successfull-registration',
    FailedRegistration = 'failed_registration',
    SubscribeLink = 'subscribe-link',
    RflzLoaded = 'rflz-loaded',
    RflzSuccessful = 'rflz-successful',
    RflzFailed = 'rflz-failed',
    RefreshSignalSent = 'refresh-signal-sent',
    RefreshTextSent = 'refresh-text-sent',
    RegisterClicked = 'register-clicked',
    PresentRegistration = 'present-registration',
    Continue = 'continue',
    RtcContinue = 'rtc-continue',
    ViewOtherSubscriptionOptions = 'view-other-subscription-options',
    GetSxmOutsideTheCar = 'get-sxm-out-the-car',
    GetSxmInTheCarPlusStreaming = 'get-sxm-in-the-car-plus-streaming',
    EnterVINSuccessful = 'enter-vin-successful',
    EnterRadioIDSuccessful = 'enter-radioid-successful',
    LoginInfoSuccessful = 'login-info-successful',
    AccordionEdit = 'edit-cta-in-accordion',
    EnterLicensePlateSuccessful = 'enter-license-plate-successful',
    StudentVerificationStatus = 'student-verification-status',
    StudentReverificationStatus = 'student-reverification-status',
    DetailsAccordionChevron = 'details-accordion-chevron',
    GenericButtonClick = 'generic-button-click',
    AmazonSupportLinkClick = 'amazon-support-link-click',
    PromoCodeSuccessful = 'promo-code-successful',
    PromoCodeFailed = 'promo-code-failed',
    PromoCodeFormLoaded = 'promo-code-form-loaded',
}
