export type BillingCardComponent =
    | 'MARKETING'
    | 'BILLING_WITH_AUTOMATED_PAYMENT'
    | 'BILLING_WITH_MAKE_PAYMENT'
    | 'BILLING_WITH_NO_PAYMENT_DUE'
    | 'BILLING_WITH_NO_PAYMENT_DUE_AUTOMATED'
    | 'BILLING_WITH_TRIALER_NO_PAYMENT_DUE'
    | 'BILLING_WITH_TRIALER_NO_PAYMENT_DUE_WITH_FOLLOWON';
