export * from './lib/module-with-translation.module';
export * from './lib/package-description-translations.service';
export * from './lib/object-tokenizer.service';
export * from './lib/url-helper.service';
export * from './lib/package-description-translations.resolver';
export * from './lib/lang-pref/normalize-lang-pref-helper.service';
export * from './lib/lang-pref/lang-pref-url-handler.module';
export * from './lib/translation-override-helpers';
export * from './lib/package-description-translations-can-activate.service';
